In [1]:
import pandas as pd
import numpy as np

In [4]:
boder = pd.read_csv("Boder_index_by_page_timestream_tableau.csv")
others = pd.read_csv("totals.csv")

In [3]:
boder

,id,last_name,first_name,page_num,keyword,parent_keyword,inv_total_pages,inv_seg_ratio,list1,list2
0,56,Kimmelmann,Abraham,1,ORT,organizations,128,0.781250,1,0.781000
1,56,Kimmelmann,Abraham,1,Dabrowa-Gornicza,time and place,128,0.781250,1,0.781000
2,56,Kimmelmann,Abraham,1,Geneva,time and place,128,0.781250,1,0.781000
3,56,Kimmelmann,Abraham,3,Children,people,128,2.343750,2,0.437000
4,56,Kimmelmann,Abraham,3,Children,people,128,2.343750,3,0.344000
5,56,Kimmelmann,Abraham,3,Curfew,discrimination,128,2.343750,2,0.437000
6,56,Kimmelmann,Abraham,3,Curfew,discrimination,128,2.343750,3,0.344000
7,56,Kimmelmann,Abraham,3,Passports,politics,128,2.343750,2,0.437000
8,56,Kimmelmann,Abraham,3,Passports,politics,128,2.343750,3,0.344000
9,56,Kimmelmann,Abraham,4,Confiscations,discrimination,128,3.125000,3,0.656000
10,56,Kimmelmann,Abraham,4,Confiscations,discrimination,128,3.125000,4,0.125000
11,56,Kimmelmann,Abraham,4,Food,daily life,128,3.125000,3,0.656000
12,56,Kimmelmann,Abraham,4,Food,daily life,128,3.125000,4,0.125000
13,56,Kimmelmann,Abraham,4,Starvation,mistreatment and death,128,3.125000,3,0.656000
14,56,Kimmelmann,Abraham,4,Starvation,mistreatment and death,128,3.125000,4,0.125000
15,56,Kimmelmann,Abraham,5,Ghetto,captivity,128,3.906250,4,0.906000
16,56,Kimmelmann,Abraham,6,Work,forced labor,128,4.687500,4,0.093000
17,56,Kimmelmann,Abraham,6,Work,forced labor,128,4.687500,5,0.688000
18,56,Kimmelmann,Abraham,7,Physical mistreatment,mistreatment and death,128,5.468750,5,0.312000
19,56,Kimmelmann,Abraham,7,Physical mistreatment,mistreatment and death,128,5.468750,6,0.469000
20,56,Kimmelmann,Abraham,7,Weather,captivity,128,5.468750,5,0.312000
21,56,Kimmelmann,Abraham,7,Weather,captivity,128,5.468750,6,0.469000
22,56,Kimmelmann,Abraham,7,Work,forced labor,128,5.468750,5,0.312000
23,56,Kimmelmann,Abraham,7,Work,forced labor,128,5.468750,6,0.469000
24,56,Kimmelmann,Abraham,8,Black Market,economics,128,6.250000,6,0.531000
25,56,Kimmelmann,Abraham,8,Black Market,economics,128,6.250000,7,0.250000
26,56,Kimmelmann,Abraham,10,Confiscations,discrimination,128,7.812500,8,0.812000
27,56,Kimmelmann,Abraham,11,Raids,captivity,128,8.593750,8,0.187000
28,56,Kimmelmann,Abraham,11,Raids,captivity,128,8.593750,9,0.594000
29,56,Kimmelmann,Abraham,11,Sosnowiec,time and place,128,8.593750,8,0.187000
...,...,...,...,...,...,...,...,...,...,...
15073,26,Franz,Hildegarde,3102,Newark,time and place,23,91.304348,88,1.000000
15074,26,Franz,Hildegarde,3102,Newark,time and place,23,91.304348,89,1.000000
15075,26,Franz,Hildegarde,3102,Newark,time and place,23,91.304348,90,1.000000
15076,26,Franz,Hildegarde,3102,Newark,time and place,23,91.304348,91,1.000000
15077,26,Franz,Hildegarde,3102,Newark,time and place,23,91.304348,92,0.304000
15078,26,Franz,Hildegarde,3103,Auschwitz,time and place,23,95.652174,92,0.695826
15079,26,Franz,Hildegarde,3103,Auschwitz,time and place,23,95.652174,93,1.000000
15080,26,Franz,Hildegarde,3103,Auschwitz,time and place,23,95.652174,94,1.000000
15081,26,Franz,Hildegarde,3103,Auschwitz,time and place,23,95.652174,95,1.000000
15082,26,Franz,Hildegarde,3103,Auschwitz,time and place,23,95.652174,96,0.652000
15083,26,Franz,Hildegarde,3103,Bergen-Belsen,time and place,23,95.652174,92,0.695826
15084,26,Franz,Hildegarde,3103,Bergen-Belsen,time and place,23,95.652174,93,1.000000
15085,26,Franz,Hildegarde,3103,Bergen-Belsen,time and place,23,95.652174,94,1.000000
15086,26,Franz,Hildegarde,3103,Bergen-Belsen,time and place,23,95.652174,95,1.000000
15087,26,Franz,Hildegarde,3103,Bergen-Belsen,time and place,23,95.652174,96,0.652000
15088,26,Franz,Hildegarde,3103,Posen,time and place,23,95.652174,92,0.695826
15089,26,Franz,Hildegarde,3103,Posen,time and place,23,95.652174,93,1.000000
15090,26,Franz,Hildegarde,3103,Posen,time and place,23,95.652174,94,1.000000
15091,26,Franz,Hildegarde,3103,Posen,time and place,23,95.652174,95,1.000000
15092,26,Franz,Hildegarde,3103,Posen,time and place,23,95.652174,96,0.652000
15093,26,Franz,Hildegarde,3104,UNRRA,post-conflict,23,100.000000,96,0.347826
15094,26,Franz,Hildegarde,3104,UNRRA,post-conflict,23,100.000000,97,1.000000
15095,26,Franz,Hildegarde,3104,UNRRA,post-conflict,23,100.000000,98,1.000000
15096,26,Franz,Hildegarde,3104,UNRRA,post-conflict,23,100.000000,99,1.000000
15097,26,Franz,Hildegarde,3104,UNRRA,post-conflict,23,100.000000,100,1.000000
15098,26,Franz,Hildegarde,3104,Funkenkasernen,time and place,23,100.000000,96,0.347826
15099,26,Franz,Hildegarde,3104,Funkenkasernen,time and place,23,100.000000,97,1.000000
15100,26,Franz,Hildegarde,3104,Funkenkasernen,time and place,23,100.000000,98,1.000000
15101,26,Franz,Hildegarde,3104,Funkenkasernen,time and place,23,100.000000,99,1.000000
15102,26,Franz,Hildegarde,3104,Funkenkasernen,time and place,23,100.000000,100,1.000000

In [7]:
others

,group_id,term_id,term_name,percentile,value,Unnamed: 5
0,9,78882,time and place (CONTAINER ONLY),1,12,NaN
1,9,78824,daily life,1,2,NaN
2,9,12360,economics (CONTAINER ONLY),1,1,NaN
3,9,78816,people (CONTAINER ONLY),1,2,NaN
4,9,78882,time and place (CONTAINER ONLY),2,61,NaN
5,9,78824,daily life,2,19,NaN
6,9,10481,culture,2,2,NaN
7,9,12360,economics (CONTAINER ONLY),2,4,NaN
8,9,78825,organizations (CONTAINER ONLY),2,3,NaN
9,9,78816,people (CONTAINER ONLY),2,1,NaN
10,9,14674,religion and philosophy (CONTAINER ONLY),2,1,NaN
11,9,25855,discrimination (CONTAINER ONLY),2,1,NaN
12,9,15485,government,2,3,NaN
13,9,78882,time and place (CONTAINER ONLY),3,45,NaN
14,9,78825,organizations (CONTAINER ONLY),3,2,NaN
15,9,78824,daily life,3,15,NaN
16,9,78816,people (CONTAINER ONLY),3,9,NaN
17,9,12360,economics (CONTAINER ONLY),3,6,NaN
18,9,10481,culture,3,2,NaN
19,9,25855,discrimination (CONTAINER ONLY),3,1,NaN
20,9,43485,world histories,3,3,NaN
21,9,14674,religion and philosophy (CONTAINER ONLY),3,1,NaN
22,9,13170,feelings and thoughts (CONTAINER ONLY),3,2,NaN
23,9,15485,government,3,2,NaN
24,9,78758,movement (CONTAINER ONLY),3,3,NaN
25,9,25855,discrimination (CONTAINER ONLY),4,2,NaN
26,9,13170,feelings and thoughts (CONTAINER ONLY),4,4,NaN
27,9,10481,culture,4,6,NaN
28,9,78824,daily life,4,15,NaN
29,9,78816,people (CONTAINER ONLY),4,5,NaN
...,...,...,...,...,...,...
28045,10,78882,time and place (CONTAINER ONLY),85,4,NaN
28046,10,10481,culture,85,3,NaN
28047,10,12360,economics (CONTAINER ONLY),85,1,NaN
28048,10,6093,post-conflict (CONTAINER ONLY),86,1,NaN
28049,10,13170,feelings and thoughts (CONTAINER ONLY),86,1,NaN
28050,10,15267,captivity (CONTAINER ONLY),86,1,NaN
28051,10,15485,government,87,1,NaN
28052,10,78824,daily life,88,1,NaN
28053,10,78882,time and place (CONTAINER ONLY),88,1,NaN
28054,10,10481,culture,89,2,NaN
28055,10,13170,feelings and thoughts (CONTAINER ONLY),89,1,NaN
28056,10,28607,still and moving images,89,1,NaN
28057,10,12360,economics (CONTAINER ONLY),89,1,NaN
28058,10,78848,health,89,1,NaN
28059,10,78824,daily life,90,1,NaN
28060,10,13170,feelings and thoughts (CONTAINER ONLY),92,1,NaN
28061,10,6093,post-conflict (CONTAINER ONLY),93,1,NaN
28062,10,28607,still and moving images,93,8,NaN
28063,10,28607,still and moving images,94,5,NaN
28064,10,78824,daily life,94,1,NaN
28065,10,78882,time and place (CONTAINER ONLY),94,2,NaN
28066,10,28607,still and moving images,95,12,NaN
28067,10,6093,post-conflict (CONTAINER ONLY),95,1,NaN
28068,10,15485,government,95,1,NaN
28069,10,28607,still and moving images,96,15,NaN
28070,10,28607,still and moving images,97,14,NaN
28071,10,28607,still and moving images,98,11,NaN
28072,10,15485,government,98,1,NaN
28073,10,28607,still and moving images,99,9,NaN
28074,10,10481,culture,99,1,NaN

# Goal: Merge the df together

! It is a bad idea to append Boder into this data! They are counted in different ways. Unless we normalize Boder, we cannot make comparison of counts. But normalization gets rid of difference in counts. We cannot bind Boder with 
- there are 99 segments in totals.
- we want to exlude the not related files in totals. We only want: 
  - 44 = Nanjing
  - 31 = Tutsi (Rwanda)
  - 2 = Jewish Holocaust survivors  
  - 46 = Armenian
- for others, we need to clean it:
  - get rid of " (CONTAINER ONLY)" in the tern_name
  - ignore "Unnamed: 5" column
- finally, we need to generate a new df to replace the old names. We will use the column names from others.
- we only expect to see timestreams, but also want to try other cross-group analysis in Tableau.

In [9]:
boder=boder[boder.list1!=100]

In [15]:
others=others[others["group_id"].isin([44,31,2,46])]

In [61]:
others

,group_id,term_id,term_name,percentile,value,Unnamed: 5
15198,46,78882,time and place (CONTAINER ONLY),1,16,NaN
15199,46,78824,daily life,1,3,NaN
15200,46,12360,economics (CONTAINER ONLY),1,3,NaN
15201,46,78816,people (CONTAINER ONLY),1,2,NaN
15202,46,14674,religion and philosophy (CONTAINER ONLY),1,3,NaN
15203,46,12360,economics (CONTAINER ONLY),2,1,NaN
15204,46,78882,time and place (CONTAINER ONLY),2,26,NaN
15205,46,78824,daily life,2,2,NaN
15206,46,78816,people (CONTAINER ONLY),2,8,NaN
15207,46,15485,government,2,1,NaN
15208,46,43485,world histories,2,1,NaN
15209,46,10481,culture,2,1,NaN
15210,46,78758,movement (CONTAINER ONLY),2,4,NaN
15211,46,14674,religion and philosophy (CONTAINER ONLY),2,3,NaN
15212,46,13170,feelings and thoughts (CONTAINER ONLY),3,5,NaN
15213,46,78816,people (CONTAINER ONLY),3,11,NaN
15214,46,78824,daily life,3,9,NaN
15215,46,78882,time and place (CONTAINER ONLY),3,20,NaN
15216,46,10481,culture,3,2,NaN
15217,46,28607,still and moving images,3,4,NaN
15218,46,12460,discrimination responses (CONTAINER ONLY),3,5,NaN
15219,46,12360,economics (CONTAINER ONLY),3,2,NaN
15220,46,78758,movement (CONTAINER ONLY),3,4,NaN
15221,46,15485,government,3,2,NaN
15222,46,78826,mistreatment and death (CONTAINER ONLY),3,1,NaN
15223,46,43485,world histories,3,1,NaN
15224,46,15267,captivity (CONTAINER ONLY),3,1,NaN
15225,46,14674,religion and philosophy (CONTAINER ONLY),3,1,NaN
15226,46,78824,daily life,4,7,NaN
15227,46,10481,culture,4,1,NaN
...,...,...,...,...,...,...
24756,2,15267,captivity (CONTAINER ONLY),98,72,NaN
24757,2,78758,movement (CONTAINER ONLY),98,112,NaN
24758,2,78937,politics (CONTAINER ONLY),98,15,NaN
24759,2,78848,health,98,12,NaN
24760,2,15346,liberation,98,7,NaN
24761,2,43485,world histories,98,33,NaN
24762,2,12332,refugee experiences (CONTAINER ONLY),98,24,NaN
24763,2,4617,forced labor,98,9,NaN
24764,2,28607,still and moving images,99,30380,NaN
24765,2,6093,post-conflict (CONTAINER ONLY),99,1721,NaN
24766,2,78816,people (CONTAINER ONLY),99,1581,NaN
24767,2,78825,organizations (CONTAINER ONLY),99,172,NaN
24768,2,13170,feelings and thoughts (CONTAINER ONLY),99,1458,NaN
24769,2,10481,culture,99,628,NaN
24770,2,15485,government,99,541,NaN
24771,2,78882,time and place (CONTAINER ONLY),99,1780,NaN
24772,2,15267,captivity (CONTAINER ONLY),99,81,NaN
24773,2,12332,refugee experiences (CONTAINER ONLY),99,32,NaN
24774,2,12360,economics (CONTAINER ONLY),99,211,NaN
24775,2,78824,daily life,99,532,NaN
24776,2,25855,discrimination (CONTAINER ONLY),99,57,NaN
24777,2,43485,world histories,99,22,NaN
24778,2,12460,discrimination responses (CONTAINER ONLY),99,115,NaN
24779,2,78848,health,99,34,NaN
24780,2,78758,movement (CONTAINER ONLY),99,166,NaN
24781,2,14674,religion and philosophy (CONTAINER ONLY),99,111,NaN
24782,2,4617,forced labor,99,13,NaN
24783,2,78826,mistreatment and death (CONTAINER ONLY),99,16,NaN
24784,2,78937,politics (CONTAINER ONLY),99,30,NaN
24785,2,15346,liberation,99,14,NaN

In [63]:
others = others.drop(columns=["Unnamed: 5"])

In [64]:
others = others.drop(columns=["term_name"])

In [65]:
others

       group_id  term_id percentile  value
15198        46    78882          1     16
15199        46    78824          1      3
15200        46    12360          1      3
15201        46    78816          1      2
15202        46    14674          1      3
15203        46    12360          2      1
15204        46    78882          2     26
15205        46    78824          2      2
15206        46    78816          2      8
15207        46    15485          2      1
15208        46    43485          2      1
15209        46    10481          2      1
15210        46    78758          2      4
15211        46    14674          2      3
15212        46    13170          3      5
15213        46    78816          3     11
15214        46    78824          3      9
15215        46    78882          3     20
15216        46    10481          3      2
15217        46    28607          3      4
15218        46    12460          3      5
15219        46    12360          3      2
15220        46    78758          3      4
15221        46    15485          3      2
15222        46    78826          3      1
15223        46    43485          3      1
15224        46    15267          3      1
15225        46    14674          3      1
15226        46    78824          4      7
15227        46    10481          4      1
...         ...      ...        ...    ...
24756         2    15267         98     72
24757         2    78758         98    112
24758         2    78937         98     15
24759         2    78848         98     12
24760         2    15346         98      7
24761         2    43485         98     33
24762         2    12332         98     24
24763         2     4617         98      9
24764         2    28607         99  30380
24765         2     6093         99   1721
24766         2    78816         99   1581
24767         2    78825         99    172
24768         2    13170         99   1458
24769         2    10481         99    628
24770         2    15485         99    541
24771         2    78882         99   1780
24772         2    15267         99     81
24773         2    12332         99     32
24774         2    12360         99    211
24775         2    78824         99    532
24776         2    25855         99     57
24777         2    43485         99     22
24778         2    12460         99    115
24779         2    78848         99     34
24780         2    78758         99    166
24781         2    14674         99    111
24782         2     4617         99     13
24783         2    78826         99     16
24784         2    78937         99     30
24785         2    15346         99     14

[6656 rows x 4 columns]

In [58]:
# tern_name_all
term_name_all=[
    "health",#78848,
    "forced labor",#4617,
    "time and place",#78882,
    "captivity",#15267,
    "movement",#78758,
    "discrimination responses",#12460,
    "refugee experiences",#12332,
    "still and moving images",#28607,
    "economics",#12360,
    "post-conflict",#6093,
    "religion and philosophy",#14674,
    "politics",#78937,
    "world histories",#43485,
    "people",#78816,
    "daily life",#78824,
    "organizations",#78825,
    "mistreatment and death",#78826,
    "culture",#10481,
    "feelings and thoughts",#13170,
    "liberation",#15346,
    "weapons",#81782,
    "government",#15485,
    "discrimination"#25855
]

In [59]:
len(term_name_all)

23

In [60]:
term_name_all

['health',
 'forced labor',
 'time and place',
 'captivity',
 'movement',
 'discrimination responses',
 'refugee experiences',
 'still and moving images',
 'economics',
 'post-conflict',
 'religion and philosophy',
 'politics',
 'world histories',
 'people',
 'daily life',
 'organizations',
 'mistreatment and death',
 'culture',
 'feelings and thoughts',
 'liberation',
 'weapons',
 'government',
 'discrimination']

In [53]:
# term_id_all
term_id_all = [
    78848,
    4617,
    78882,
    15267,
    78758,
    12460,
    12332,
    28607,
    12360,
    6093,
    14674,
    78937,
    43485,
    78816,
    78824,
    78825,
    78826,
    10481,
    13170,
    15346,
    81782,
    15485,
    25855
]

In [54]:
len(term_id_all)

23

In [66]:
meta = pd.DataFrame()

In [67]:
meta["term_id"]=term_id_all
meta["term_name"]=term_name_all

In [80]:
meta = meta.set_index(["term_id"])

In [81]:
meta

                        term_name
term_id
78848                      health
4617                 forced labor
78882              time and place
15267                   captivity
78758                    movement
12460    discrimination responses
12332         refugee experiences
28607     still and moving images
12360                   economics
6093                post-conflict
14674     religion and philosophy
78937                    politics
43485             world histories
78816                      people
78824                  daily life
78825               organizations
78826      mistreatment and death
10481                     culture
13170       feelings and thoughts
15346                  liberation
81782                     weapons
15485                  government
25855              discrimination

In [86]:
others=others[others["term_id"].isin(term_id_all)].reset_index(drop=True)

In [95]:
type(others.term_id[0])

numpy.int64

In [100]:
others["term_name"]=others.term_id.apply(lambda x: meta.term_name[x])

In [104]:
others

      group_id  term_id percentile  value                 term_name
0           46    78882          1     16            time and place
1           46    78824          1      3                daily life
2           46    12360          1      3                 economics
3           46    78816          1      2                    people
4           46    14674          1      3   religion and philosophy
5           46    12360          2      1                 economics
6           46    78882          2     26            time and place
7           46    78824          2      2                daily life
8           46    78816          2      8                    people
9           46    15485          2      1                government
10          46    43485          2      1           world histories
11          46    10481          2      1                   culture
12          46    78758          2      4                  movement
13          46    14674          2      3   religion and philosophy
14          46    13170          3      5     feelings and thoughts
15          46    78816          3     11                    people
16          46    78824          3      9                daily life
17          46    78882          3     20            time and place
18          46    10481          3      2                   culture
19          46    28607          3      4   still and moving images
20          46    12460          3      5  discrimination responses
21          46    12360          3      2                 economics
22          46    78758          3      4                  movement
23          46    15485          3      2                government
24          46    78826          3      1    mistreatment and death
25          46    43485          3      1           world histories
26          46    15267          3      1                 captivity
27          46    14674          3      1   religion and philosophy
28          46    78824          4      7                daily life
29          46    10481          4      1                   culture
...        ...      ...        ...    ...                       ...
6602         2    15267         98     72                 captivity
6603         2    78758         98    112                  movement
6604         2    78937         98     15                  politics
6605         2    78848         98     12                    health
6606         2    15346         98      7                liberation
6607         2    43485         98     33           world histories
6608         2    12332         98     24       refugee experiences
6609         2     4617         98      9              forced labor
6610         2    28607         99  30380   still and moving images
6611         2     6093         99   1721             post-conflict
6612         2    78816         99   1581                    people
6613         2    78825         99    172             organizations
6614         2    13170         99   1458     feelings and thoughts
6615         2    10481         99    628                   culture
6616         2    15485         99    541                government
6617         2    78882         99   1780            time and place
6618         2    15267         99     81                 captivity
6619         2    12332         99     32       refugee experiences
6620         2    12360         99    211                 economics
6621         2    78824         99    532                daily life
6622         2    25855         99     57            discrimination
6623         2    43485         99     22           world histories
6624         2    12460         99    115  discrimination responses
6625         2    78848         99     34                    health
6626         2    78758         99    166                  movement
6627         2    14674         99    111   religion and philosophy
6628         2     4617         99     13              forced labor
6629         2    78826         99     16    mistreatment and death
6630         2    78937         99     30                  politics
6631         2    15346         99     14                liberation

[6632 rows x 5 columns]

In [106]:
list(set(boder.parent_keyword))

['movement',
 'discrimination',
 'health',
 'world histories',
 'forced labor',
 'feelings and thoughts',
 'liberation',
 'daily life',
 'post-conflict',
 'government',
 'religion and philosophy',
 'discrimination ',
 'discrimination responses',
 'people',
 'mistreatment and death',
 'weapons',
 'economics',
 'culture',
 'captivity',
 'time and place',
 'politics',
 'organizations']

Probably still need to encode into the same data set?

In [108]:
others2=pd.DataFrame()

In [109]:
others2["group_id"] = list(others.group_id)+[0]*len(boder)
others2["term_name"] = list(others.term_name)+list(boder.parent_keyword)
others2["percentile"] = list(others.percentile)+list(boder.list1)
others2["value"] = list(others.value)+list(boder.list2)

In [112]:
others2.value = others2.value.apply(lambda x: round(x,3))

In [113]:
others2

       group_id                 term_name percentile   value
0            46            time and place          1  16.000
1            46                daily life          1   3.000
2            46                 economics          1   3.000
3            46                    people          1   2.000
4            46   religion and philosophy          1   3.000
5            46                 economics          2   1.000
6            46            time and place          2  26.000
7            46                daily life          2   2.000
8            46                    people          2   8.000
9            46                government          2   1.000
10           46           world histories          2   1.000
11           46                   culture          2   1.000
12           46                  movement          2   4.000
13           46   religion and philosophy          2   3.000
14           46     feelings and thoughts          3   5.000
15           46                    people          3  11.000
16           46                daily life          3   9.000
17           46            time and place          3  20.000
18           46                   culture          3   2.000
19           46   still and moving images          3   4.000
20           46  discrimination responses          3   5.000
21           46                 economics          3   2.000
22           46                  movement          3   4.000
23           46                government          3   2.000
24           46    mistreatment and death          3   1.000
25           46           world histories          3   1.000
26           46                 captivity          3   1.000
27           46   religion and philosophy          3   1.000
28           46                daily life          4   7.000
29           46                   culture          4   1.000
...         ...                       ...        ...     ...
21667         0            time and place         92   0.304
21668         0            time and place         87   0.044
21669         0            time and place         88   1.000
21670         0            time and place         89   1.000
21671         0            time and place         90   1.000
21672         0            time and place         91   1.000
21673         0            time and place         92   0.304
21674         0            time and place         92   0.696
21675         0            time and place         93   1.000
21676         0            time and place         94   1.000
21677         0            time and place         95   1.000
21678         0            time and place         96   0.652
21679         0            time and place         92   0.696
21680         0            time and place         93   1.000
21681         0            time and place         94   1.000
21682         0            time and place         95   1.000
21683         0            time and place         96   0.652
21684         0            time and place         92   0.696
21685         0            time and place         93   1.000
21686         0            time and place         94   1.000
21687         0            time and place         95   1.000
21688         0            time and place         96   0.652
21689         0             post-conflict         96   0.348
21690         0             post-conflict         97   1.000
21691         0             post-conflict         98   1.000
21692         0             post-conflict         99   1.000
21693         0            time and place         96   0.348
21694         0            time and place         97   1.000
21695         0            time and place         98   1.000
21696         0            time and place         99   1.000

[21697 rows x 4 columns]

In [115]:
others2=others2[others2.percentile!=100]

In [120]:
list(set(others2.term_name))

['movement',
 'discrimination',
 'health',
 'refugee experiences',
 'world histories',
 'forced labor',
 'still and moving images',
 'feelings and thoughts',
 'liberation',
 'daily life',
 'government',
 'post-conflict',
 'religion and philosophy',
 'discrimination ',
 'discrimination responses',
 'people',
 'mistreatment and death',
 'weapons',
 'economics',
 'culture',
 'captivity',
 'time and place',
 'politics',
 'organizations']

In [121]:
others2=others2.replace("discrimination ","discrimination")

In [122]:
list(set(others2.term_name))

['movement',
 'discrimination',
 'health',
 'refugee experiences',
 'world histories',
 'forced labor',
 'still and moving images',
 'feelings and thoughts',
 'liberation',
 'daily life',
 'government',
 'post-conflict',
 'religion and philosophy',
 'discrimination responses',
 'people',
 'mistreatment and death',
 'weapons',
 'economics',
 'culture',
 'captivity',
 'time and place',
 'politics',
 'organizations']

In [123]:
len(list(set(others2.term_name)))

23

In [124]:
others2.to_csv("totoals_tableau.csv",index=False)