While manually input the range of index for the 70 interviewees, I found there are more alias than I imaged. Some of them even have 3 alias. This could be an interesting research question: why they have different alais? Several guesses: 1. Mistakes by interviwers; 2. Different names in different languages; 3. interviewees want to hide their identities.

Both source and result are here: https://docs.google.com/spreadsheets/d/1BB9m2y35Z6GJeFwJJRp-WteH3EDuibwB-WB0rGDiN7Y/edit#gid=2117971806

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Boder Data - Meta (1).csv")

In [3]:
df.head()

,interviewee_id,interviewee_last,interviewee_first,interviewee_index_range,interviewee_index_list,interviewee_count,interviewer_count,diff,ratio,gender,...,first_alias2,last_alias3,first_alias3,original_last,original_first,interviewed_multi_times?,where_want_to_go?,related_to,notes,additional_info
0,1,A.,Ilmar,NaN,NaN,1951.0,1395.0,556.0,1.398566,Male,...,NaN,NaN,NaN,A.,Ilmar,NaN,NaN,NaN,NaN,NaN
1,2,Barzilai,Nino,NaN,NaN,1326.0,440.0,886.0,3.013636,Male,...,NaN,NaN,NaN,Barzilai,Nino,NaN,NaN,NaN,NaN,NaN
2,3,Bassfreund,Jurgen,276-318,NaN,8705.0,2231.0,6474.0,3.901838,Male,...,Jorn,Juergen,Bassfreund,Bassfreund,Jürgen,yes,NaN,NaN,NaN,NaN
3,4,Benmayor,Rita,NaN,NaN,1819.0,2219.0,-400.0,0.819739,Female,...,NaN,NaN,NaN,Benmayor,Rita,NaN,NaN,NaN,NaN,NaN
4,5,Billi,Tomas,NaN,NaN,1470.0,820.0,650.0,1.792683,Male,...,NaN,NaN,NaN,Billi,Tomas,NaN,NaN,NaN,NaN,NaN

In [5]:
df.interviewee_index_range[2]

'276-318'

In [16]:
type(df.interviewee_index_range[2])

str

In the column of interviewee_index_range, ranges are str while missing values are np.nan

In [7]:
def to_range(str1):
    for i in range(len(str1)):
        if str1[i]=="-":
            a = int(str1[:i])
            b = int(str1[i+1:])
            return(list(range(a,b+1)))

In [19]:
to_range(df.interviewee_index_range[2])

[276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318]

In [22]:
df.interviewee_index_range = df.interviewee_index_range.fillna("")

In [23]:
df

,interviewee_id,interviewee_last,interviewee_first,interviewee_index_range,interviewee_index_list,interviewee_count,interviewer_count,diff,ratio,gender,...,first_alias2,last_alias3,first_alias3,original_last,original_first,interviewed_multi_times?,where_want_to_go?,related_to,notes,additional_info
0,1,A.,Ilmar,,NaN,1951.0,1395.0,556.0,1.398566,Male,...,NaN,NaN,NaN,A.,Ilmar,NaN,NaN,NaN,NaN,NaN
1,2,Barzilai,Nino,,NaN,1326.0,440.0,886.0,3.013636,Male,...,NaN,NaN,NaN,Barzilai,Nino,NaN,NaN,NaN,NaN,NaN
2,3,Bassfreund,Jurgen,276-318,NaN,8705.0,2231.0,6474.0,3.901838,Male,...,Jorn,Juergen,Bassfreund,Bassfreund,Jürgen,yes,NaN,NaN,NaN,NaN
3,4,Benmayor,Rita,,NaN,1819.0,2219.0,-400.0,0.819739,Female,...,NaN,NaN,NaN,Benmayor,Rita,NaN,NaN,NaN,NaN,NaN
4,5,Billi,Tomas,,NaN,1470.0,820.0,650.0,1.792683,Male,...,NaN,NaN,NaN,Billi,Tomas,NaN,NaN,NaN,NaN,NaN
5,6,Bisenhaus,Polia,865-886,NaN,2581.0,1339.0,1242.0,1.927558,Female,...,NaN,NaN,NaN,Bisenhaus,Polia,NaN,NaN,NaN,truly multilingual transcript,NaN
6,7,B.,Janis,1033-1063,NaN,1637.0,1212.0,425.0,1.350660,Male,...,NaN,NaN,NaN,B.,Janis,NaN,NaN,NaN,NaN,NaN
7,8,[last name unknown],Boguslaw,,NaN,752.0,139.0,613.0,5.410072,Male,...,NaN,NaN,NaN,[last name unknown],Boguslaw,NaN,NaN,NaN,NaN,NaN
8,9,Bondy,Nelly,1500-1580,NaN,10654.0,3312.0,7342.0,3.216787,Female,...,NaN,NaN,NaN,Bondy,Nelly,NaN,NaN,NaN,NaN,NaN
9,10,Borgman,[first name unknown],,NaN,1027.0,680.0,347.0,1.510294,NaN,...,NaN,NaN,NaN,Borgman,[first name unknown],NaN,NaN,NaN,NaN,NaN
10,11,Bramson,Jacques,732-826,NaN,15577.0,3395.0,12182.0,4.588218,Male,...,NaN,NaN,NaN,Bramson,Jacques,NaN,NaN,NaN,NaN,NaN
11,12,Braun,Anna,690-730,NaN,5576.0,2706.0,2870.0,2.060606,Female,...,NaN,NaN,NaN,Braun,Anna,NaN,NaN,NaN,NaN,NaN
12,13,Breslauer,Arthur,,NaN,1402.0,1199.0,203.0,1.169308,Male,...,NaN,NaN,NaN,Breslauer,Arthur,NaN,NaN,NaN,NaN,NaN
13,14,Brin,Isaac,,NaN,4757.0,928.0,3829.0,5.126078,Male,...,NaN,NaN,NaN,Brin,Itzhak,NaN,NaN,NaN,NaN,NaN
14,15,Button,Eda,,NaN,4802.0,1539.0,3263.0,3.120208,Female,...,NaN,NaN,NaN,Button,Eda,NaN,NaN,15,wife of 15 (may not actually be related accord...,NaN
15,16,Button,Jacob,,NaN,2224.0,775.0,1449.0,2.869677,Male,...,NaN,NaN,NaN,Button,Jacob,NaN,NaN,14,husband of 14 (may not actually be related acc...,NaN
16,17,Czolopicki,Boleslaw,,NaN,868.0,563.0,305.0,1.541741,Male,...,NaN,NaN,NaN,Czolopicki,Boleslaw,NaN,NaN,NaN,NaN,NaN
17,18,Deutsch,Yanusch,,NaN,4387.0,1208.0,3179.0,3.631623,Male,...,NaN,NaN,NaN,Deutsch,Yanusch,NaN,NaN,NaN,NaN,NaN
18,19,Eisenberg,Kalman,2533-2570,NaN,8603.0,1119.0,7484.0,7.688114,Male,...,NaN,NaN,NaN,Eisenberg,Kalman,NaN,NaN,NaN,NaN,NaN
19,20,Epstein-Kozlowski,Nechama,2592-2668,NaN,13676.0,2279.0,11397.0,6.000878,Female,...,NaN,NaN,NaN,Epstein-Kozlowski,Nechama,NaN,NaN,NaN,NaN,NaN
20,21,Feneger,[first name unknown],,NaN,231.0,362.0,-131.0,0.638122,Male,...,NaN,NaN,NaN,Feneger,[first name unknown],NaN,NaN,NaN,NaN,NaN
21,22,Ferber,Joseph,2855-2876,NaN,3815.0,1074.0,2741.0,3.552142,Male,...,NaN,NaN,NaN,Ferber,Joseph,NaN,NaN,NaN,NaN,NaN
22,23,Ferdinansk,Victor,3040-3054,NaN,1780.0,1096.0,684.0,1.624088,Male,...,NaN,NaN,NaN,Ferdinansk,Victor,NaN,NaN,NaN,NaN,NaN
23,24,Feuer,Otto,887-954,NaN,9106.0,2734.0,6372.0,3.330651,Male,...,NaN,NaN,NaN,Feuer,Otto,NaN,NaN,NaN,NaN,NaN
24,25,Finkel,Nathan,,NaN,1689.0,586.0,1103.0,2.882253,Male,...,NaN,NaN,NaN,Finkel,Nathan,NaN,NaN,NaN,NaN,NaN
25,26,Franz,Hildegarde,3082-3104,NaN,2421.0,1475.0,946.0,1.641356,Female,...,NaN,NaN,NaN,Franz,Hildegarde,NaN,United States,NaN,NaN,NaN
26,27,Freilich,Esther,,NaN,948.0,698.0,250.0,1.358166,Female,...,NaN,NaN,NaN,Freilich,Esther,NaN,NaN,Freida Freilich (mother) 24,NaN,NaN
27,28,Freilich,Fania,319-363,NaN,10436.0,1061.0,9375.0,9.836004,Female,...,NaN,NaN,NaN,Freilich,Fania,NaN,NaN,Esther Freilich (daughter) 23,NaN,NaN
28,29,Perl,Abram,2112-2153,NaN,5893.0,2220.0,3673.0,2.654505,Male,...,Friedman,NaN,NaN,Friedman,Baruch,NaN,Palestine,NaN,former name friedman,NaN
29,30,Frim,Leon,,NaN,9023.0,1055.0,7968.0,8.552607,Male,...,NaN,NaN,NaN,Frim,Leon,NaN,NaN,NaN,look at the use of where,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Rosenfeld,Pinkhus,2877-2922,NaN,6286.0,2224.0,4062.0,2.826439,Male,...,NaN,NaN,NaN,Rosenfeld,Pinkhus,NaN,Palestine,NaN,NaN,NaN
89,90,Rosenwasser,Irena,1205-1278,NaN,8700.0,2869.0,5831.0,3.032415,Female,...,NaN,NaN,NaN,Rosenwasser,Irena,NaN,United States,NaN,Family in Los Angeles,NaN
90,91,Roset,Raisel,1064-1079,NaN,1576.0,795.0,781.0,1.982390,Female,...,NaN,NaN,NaN,Roset,Raisel,NaN,NaN,NaN,NaN,NaN
91,92,Rudo,[first name unknown],,NaN,1902.0,602.0,1300.0,3.159468,Female,...,NaN,NaN,NaN,Rudo,[first name unknown],NaN,NaN,NaN,"Spanish refugee taking classes at ORT,",NaN
92,93,Schacht,Nathan,,NaN,1444.0,1246.0,198.0,1.158909,NaN,...,NaN,NaN,NaN,Schacht,Nathan,NaN,NaN,NaN,NaN,NaN
93,94,Schiver,Toba,,NaN,2421.0,1987.0,434.0,1.218420,Female,...,NaN,NaN,NaN,Schiver,Toba,NaN,Palestine,NaN,Talk about how her younger sister is married b...,NaN
94,95,Schlaefrig,Friedrich,1135-1204,NaN,12657.0,2164.0,10493.0,5.848891,Male,...,NaN,NaN,NaN,Schlaefrig,Friedrich,NaN,South Africa,NaN,At the end his wife passes a message along to ...,NaN
95,96,Schrameck,Abraham,,NaN,2063.0,168.0,1895.0,12.279762,Male,...,NaN,NaN,NaN,Schrameck,Abraham,NaN,NaN,Father of Anne Marcelle Kahn,NaN,NaN
96,97,Schultze,Charlotte,2978-3000,NaN,2493.0,1653.0,840.0,1.508167,Female,...,NaN,NaN,NaN,Schultze,Charlotte,NaN,United States,NaN,"Despite not being Jewish, her husband treated ...",NaN
97,98,Schwarzfitter,Jacob,1080-1134,NaN,9490.0,1605.0,7885.0,5.912773,Male,...,NaN,NaN,NaN,Schwarzfitter,Jacob,NaN,NaN,NaN,relatives in United States,NaN
98,99,Serras,Edith,1302-1366,NaN,10289.0,2036.0,8253.0,5.053536,Female,...,NaN,NaN,NaN,Serras,Edith,NaN,NaN,NaN,NaN,"large tattoo, is askes why her tattoo is so large"
99,100,Shachnovski,Leon,1020-1032,NaN,1625.0,394.0,1231.0,4.124365,Male,...,NaN,NaN,NaN,Shachnovski,Leon,NaN,Germany,NaN,NaN,NaN
100,101,Silberbart,Gert,,NaN,6043.0,2204.0,3839.0,2.741833,Male,...,NaN,NaN,NaN,Silberbart,Gert,NaN,NaN,NaN,NaN,NaN
101,102,Skudaikiene,Brone,,NaN,579.0,486.0,93.0,1.191358,Female,...,NaN,NaN,NaN,Skudaikienė,Bronė,NaN,NaN,NaN,NaN,NaN
102,103,Sochami,Henry,,NaN,1303.0,552.0,751.0,2.360507,Male,...,NaN,NaN,NaN,Sochami,Henry,NaN,NaN,NaN,NaN,NaN
103,104,Sprecher,Max,1741-1783,NaN,8526.0,1588.0,6938.0,5.369018,Male,...,NaN,NaN,NaN,Sprecher,Max,NaN,NaN,NaN,Meyer is the middle name.,NaN
104,105,Stopnitsky,Udel,129-201,NaN,14277.0,2492.0,11785.0,5.729133,Male,...,NaN,NaN,NaN,Stopnitsky,Udel,NaN,NaN,NaN,NaN,NaN
105,106,Stumachin,Lina,,NaN,2650.0,581.0,2069.0,4.561102,Female,...,NaN,NaN,NaN,Stumachin,Lina,NaN,NaN,NaN,NaN,NaN
106,107,Suvalkaitis,Andrius,,NaN,1828.0,579.0,1249.0,3.157168,Male,...,NaN,NaN,NaN,Suvalkaitis,Andrius,NaN,NaN,NaN,NaN,NaN
107,108,Tcharnabroda,Roma,827-864,NaN,5700.0,1492.0,4208.0,3.820375,Female,...,NaN,NaN,NaN,Tcharnabroda,Roma,NaN,NaN,NaN,NaN,NaN
108,109,Tichauer,Helen,2043-2111,NaN,14026.0,2305.0,11721.0,6.085033,Female,...,NaN,NaN,NaN,Tichauer,Helen,NaN,NaN,NaN,NaN,NaN
109,110,Unikowski,Israel,1784-1849,NaN,9038.0,2458.0,6580.0,3.676973,Male,...,NaN,NaN,NaN,Unikowski,Israel,yes,NaN,NaN,NaN,NaN
110,111,Warsager,Bernard,1850-1902,NaN,9285.0,2560.0,6725.0,3.626953,Male,...,NaN,NaN,NaN,Warsager,Bernard,NaN,NaN,NaN,NaN,NaN
111,112,Weinberg,Julian,1279-1301,NaN,3241.0,767.0,2474.0,4.225554,Male,...,NaN,NaN,NaN,Weinberg,Julian,NaN,NaN,NaN,NaN,NaN
112,113,Wilf,Jacob,1473-1499,NaN,4036.0,1339.0,2697.0,3.014190,Male,...,NaN,NaN,NaN,Wilf,Jacob,NaN,NaN,NaN,NaN,NaN
113,114,Wolf,Isaac,2423-2497,NaN,11173.0,2501.0,8672.0,4.467413,Male,...,NaN,NaN,NaN,Wolf,Isaac,NaN,NaN,NaN,NaN,NaN
114,115,Zeplit,Robert,,NaN,2142.0,1981.0,161.0,1.081272,Male,...,NaN,NaN,NaN,Zeplit,Robert,NaN,NaN,NaN,NaN,NaN
115,116,Zgnilek,Bella,2571-2591,NaN,1596.0,1650.0,-54.0,0.967273,Female,...,NaN,NaN,NaN,Zgnilek,Bella,NaN,NaN,NaN,NaN,NaN
116,117,Zierer,Edith,2830-2854,NaN,2237.0,1571.0,666.0,1.423934,Female,...,NaN,NaN,NaN,Zierer,Edith,yes,NaN,NaN,NaN,NaN
117,118,Zurilis,Sophia,,NaN,2036.0,643.0,1393.0,3.166407,Female,...,NaN,NaN,NaN,Zurilis,Sophia,NaN,NaN,NaN,NaN,NaN

In [24]:
df.interviewee_index_list = df.interviewee_index_range.apply(lambda x: to_range(x))

In [25]:
df

,interviewee_id,interviewee_last,interviewee_first,interviewee_index_range,interviewee_index_list,interviewee_count,interviewer_count,diff,ratio,gender,...,first_alias2,last_alias3,first_alias3,original_last,original_first,interviewed_multi_times?,where_want_to_go?,related_to,notes,additional_info
0,1,A.,Ilmar,,None,1951.0,1395.0,556.0,1.398566,Male,...,NaN,NaN,NaN,A.,Ilmar,NaN,NaN,NaN,NaN,NaN
1,2,Barzilai,Nino,,None,1326.0,440.0,886.0,3.013636,Male,...,NaN,NaN,NaN,Barzilai,Nino,NaN,NaN,NaN,NaN,NaN
2,3,Bassfreund,Jurgen,276-318,"[276, 277, 278, 279, 280, 281, 282, 283, 284, ...",8705.0,2231.0,6474.0,3.901838,Male,...,Jorn,Juergen,Bassfreund,Bassfreund,Jürgen,yes,NaN,NaN,NaN,NaN
3,4,Benmayor,Rita,,None,1819.0,2219.0,-400.0,0.819739,Female,...,NaN,NaN,NaN,Benmayor,Rita,NaN,NaN,NaN,NaN,NaN
4,5,Billi,Tomas,,None,1470.0,820.0,650.0,1.792683,Male,...,NaN,NaN,NaN,Billi,Tomas,NaN,NaN,NaN,NaN,NaN
5,6,Bisenhaus,Polia,865-886,"[865, 866, 867, 868, 869, 870, 871, 872, 873, ...",2581.0,1339.0,1242.0,1.927558,Female,...,NaN,NaN,NaN,Bisenhaus,Polia,NaN,NaN,NaN,truly multilingual transcript,NaN
6,7,B.,Janis,1033-1063,"[1033, 1034, 1035, 1036, 1037, 1038, 1039, 104...",1637.0,1212.0,425.0,1.350660,Male,...,NaN,NaN,NaN,B.,Janis,NaN,NaN,NaN,NaN,NaN
7,8,[last name unknown],Boguslaw,,None,752.0,139.0,613.0,5.410072,Male,...,NaN,NaN,NaN,[last name unknown],Boguslaw,NaN,NaN,NaN,NaN,NaN
8,9,Bondy,Nelly,1500-1580,"[1500, 1501, 1502, 1503, 1504, 1505, 1506, 150...",10654.0,3312.0,7342.0,3.216787,Female,...,NaN,NaN,NaN,Bondy,Nelly,NaN,NaN,NaN,NaN,NaN
9,10,Borgman,[first name unknown],,None,1027.0,680.0,347.0,1.510294,NaN,...,NaN,NaN,NaN,Borgman,[first name unknown],NaN,NaN,NaN,NaN,NaN
10,11,Bramson,Jacques,732-826,"[732, 733, 734, 735, 736, 737, 738, 739, 740, ...",15577.0,3395.0,12182.0,4.588218,Male,...,NaN,NaN,NaN,Bramson,Jacques,NaN,NaN,NaN,NaN,NaN
11,12,Braun,Anna,690-730,"[690, 691, 692, 693, 694, 695, 696, 697, 698, ...",5576.0,2706.0,2870.0,2.060606,Female,...,NaN,NaN,NaN,Braun,Anna,NaN,NaN,NaN,NaN,NaN
12,13,Breslauer,Arthur,,None,1402.0,1199.0,203.0,1.169308,Male,...,NaN,NaN,NaN,Breslauer,Arthur,NaN,NaN,NaN,NaN,NaN
13,14,Brin,Isaac,,None,4757.0,928.0,3829.0,5.126078,Male,...,NaN,NaN,NaN,Brin,Itzhak,NaN,NaN,NaN,NaN,NaN
14,15,Button,Eda,,None,4802.0,1539.0,3263.0,3.120208,Female,...,NaN,NaN,NaN,Button,Eda,NaN,NaN,15,wife of 15 (may not actually be related accord...,NaN
15,16,Button,Jacob,,None,2224.0,775.0,1449.0,2.869677,Male,...,NaN,NaN,NaN,Button,Jacob,NaN,NaN,14,husband of 14 (may not actually be related acc...,NaN
16,17,Czolopicki,Boleslaw,,None,868.0,563.0,305.0,1.541741,Male,...,NaN,NaN,NaN,Czolopicki,Boleslaw,NaN,NaN,NaN,NaN,NaN
17,18,Deutsch,Yanusch,,None,4387.0,1208.0,3179.0,3.631623,Male,...,NaN,NaN,NaN,Deutsch,Yanusch,NaN,NaN,NaN,NaN,NaN
18,19,Eisenberg,Kalman,2533-2570,"[2533, 2534, 2535, 2536, 2537, 2538, 2539, 254...",8603.0,1119.0,7484.0,7.688114,Male,...,NaN,NaN,NaN,Eisenberg,Kalman,NaN,NaN,NaN,NaN,NaN
19,20,Epstein-Kozlowski,Nechama,2592-2668,"[2592, 2593, 2594, 2595, 2596, 2597, 2598, 259...",13676.0,2279.0,11397.0,6.000878,Female,...,NaN,NaN,NaN,Epstein-Kozlowski,Nechama,NaN,NaN,NaN,NaN,NaN
20,21,Feneger,[first name unknown],,None,231.0,362.0,-131.0,0.638122,Male,...,NaN,NaN,NaN,Feneger,[first name unknown],NaN,NaN,NaN,NaN,NaN
21,22,Ferber,Joseph,2855-2876,"[2855, 2856, 2857, 2858, 2859, 2860, 2861, 286...",3815.0,1074.0,2741.0,3.552142,Male,...,NaN,NaN,NaN,Ferber,Joseph,NaN,NaN,NaN,NaN,NaN
22,23,Ferdinansk,Victor,3040-3054,"[3040, 3041, 3042, 3043, 3044, 3045, 3046, 304...",1780.0,1096.0,684.0,1.624088,Male,...,NaN,NaN,NaN,Ferdinansk,Victor,NaN,NaN,NaN,NaN,NaN
23,24,Feuer,Otto,887-954,"[887, 888, 889, 890, 891, 892, 893, 894, 895, ...",9106.0,2734.0,6372.0,3.330651,Male,...,NaN,NaN,NaN,Feuer,Otto,NaN,NaN,NaN,NaN,NaN
24,25,Finkel,Nathan,,None,1689.0,586.0,1103.0,2.882253,Male,...,NaN,NaN,NaN,Finkel,Nathan,NaN,NaN,NaN,NaN,NaN
25,26,Franz,Hildegarde,3082-3104,"[3082, 3083, 3084, 3085, 3086, 3087, 3088, 308...",2421.0,1475.0,946.0,1.641356,Female,...,NaN,NaN,NaN,Franz,Hildegarde,NaN,United States,NaN,NaN,NaN
26,27,Freilich,Esther,,None,948.0,698.0,250.0,1.358166,Female,...,NaN,NaN,NaN,Freilich,Esther,NaN,NaN,Freida Freilich (mother) 24,NaN,NaN
27,28,Freilich,Fania,319-363,"[319, 320, 321, 322, 323, 324, 325, 326, 327, ...",10436.0,1061.0,9375.0,9.836004,Female,...,NaN,NaN,NaN,Freilich,Fania,NaN,NaN,Esther Freilich (daughter) 23,NaN,NaN
28,29,Perl,Abram,2112-2153,"[2112, 2113, 2114, 2115, 2116, 2117, 2118, 211...",5893.0,2220.0,3673.0,2.654505,Male,...,Friedman,NaN,NaN,Friedman,Baruch,NaN,Palestine,NaN,former name friedman,NaN
29,30,Frim,Leon,,None,9023.0,1055.0,7968.0,8.552607,Male,...,NaN,NaN,NaN,Frim,Leon,NaN,NaN,NaN,look at the use of where,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Rosenfeld,Pinkhus,2877-2922,"[2877, 2878, 2879, 2880, 2881, 2882, 2883, 288...",6286.0,2224.0,4062.0,2.826439,Male,...,NaN,NaN,NaN,Rosenfeld,Pinkhus,NaN,Palestine,NaN,NaN,NaN
89,90,Rosenwasser,Irena,1205-1278,"[1205, 1206, 1207, 1208, 1209, 1210, 1211, 121...",8700.0,2869.0,5831.0,3.032415,Female,...,NaN,NaN,NaN,Rosenwasser,Irena,NaN,United States,NaN,Family in Los Angeles,NaN
90,91,Roset,Raisel,1064-1079,"[1064, 1065, 1066, 1067, 1068, 1069, 1070, 107...",1576.0,795.0,781.0,1.982390,Female,...,NaN,NaN,NaN,Roset,Raisel,NaN,NaN,NaN,NaN,NaN
91,92,Rudo,[first name unknown],,None,1902.0,602.0,1300.0,3.159468,Female,...,NaN,NaN,NaN,Rudo,[first name unknown],NaN,NaN,NaN,"Spanish refugee taking classes at ORT,",NaN
92,93,Schacht,Nathan,,None,1444.0,1246.0,198.0,1.158909,NaN,...,NaN,NaN,NaN,Schacht,Nathan,NaN,NaN,NaN,NaN,NaN
93,94,Schiver,Toba,,None,2421.0,1987.0,434.0,1.218420,Female,...,NaN,NaN,NaN,Schiver,Toba,NaN,Palestine,NaN,Talk about how her younger sister is married b...,NaN
94,95,Schlaefrig,Friedrich,1135-1204,"[1135, 1136, 1137, 1138, 1139, 1140, 1141, 114...",12657.0,2164.0,10493.0,5.848891,Male,...,NaN,NaN,NaN,Schlaefrig,Friedrich,NaN,South Africa,NaN,At the end his wife passes a message along to ...,NaN
95,96,Schrameck,Abraham,,None,2063.0,168.0,1895.0,12.279762,Male,...,NaN,NaN,NaN,Schrameck,Abraham,NaN,NaN,Father of Anne Marcelle Kahn,NaN,NaN
96,97,Schultze,Charlotte,2978-3000,"[2978, 2979, 2980, 2981, 2982, 2983, 2984, 298...",2493.0,1653.0,840.0,1.508167,Female,...,NaN,NaN,NaN,Schultze,Charlotte,NaN,United States,NaN,"Despite not being Jewish, her husband treated ...",NaN
97,98,Schwarzfitter,Jacob,1080-1134,"[1080, 1081, 1082, 1083, 1084, 1085, 1086, 108...",9490.0,1605.0,7885.0,5.912773,Male,...,NaN,NaN,NaN,Schwarzfitter,Jacob,NaN,NaN,NaN,relatives in United States,NaN
98,99,Serras,Edith,1302-1366,"[1302, 1303, 1304, 1305, 1306, 1307, 1308, 130...",10289.0,2036.0,8253.0,5.053536,Female,...,NaN,NaN,NaN,Serras,Edith,NaN,NaN,NaN,NaN,"large tattoo, is askes why her tattoo is so large"
99,100,Shachnovski,Leon,1020-1032,"[1020, 1021, 1022, 1023, 1024, 1025, 1026, 102...",1625.0,394.0,1231.0,4.124365,Male,...,NaN,NaN,NaN,Shachnovski,Leon,NaN,Germany,NaN,NaN,NaN
100,101,Silberbart,Gert,,None,6043.0,2204.0,3839.0,2.741833,Male,...,NaN,NaN,NaN,Silberbart,Gert,NaN,NaN,NaN,NaN,NaN
101,102,Skudaikiene,Brone,,None,579.0,486.0,93.0,1.191358,Female,...,NaN,NaN,NaN,Skudaikienė,Bronė,NaN,NaN,NaN,NaN,NaN
102,103,Sochami,Henry,,None,1303.0,552.0,751.0,2.360507,Male,...,NaN,NaN,NaN,Sochami,Henry,NaN,NaN,NaN,NaN,NaN
103,104,Sprecher,Max,1741-1783,"[1741, 1742, 1743, 1744, 1745, 1746, 1747, 174...",8526.0,1588.0,6938.0,5.369018,Male,...,NaN,NaN,NaN,Sprecher,Max,NaN,NaN,NaN,Meyer is the middle name.,NaN
104,105,Stopnitsky,Udel,129-201,"[129, 130, 131, 132, 133, 134, 135, 136, 137, ...",14277.0,2492.0,11785.0,5.729133,Male,...,NaN,NaN,NaN,Stopnitsky,Udel,NaN,NaN,NaN,NaN,NaN
105,106,Stumachin,Lina,,None,2650.0,581.0,2069.0,4.561102,Female,...,NaN,NaN,NaN,Stumachin,Lina,NaN,NaN,NaN,NaN,NaN
106,107,Suvalkaitis,Andrius,,None,1828.0,579.0,1249.0,3.157168,Male,...,NaN,NaN,NaN,Suvalkaitis,Andrius,NaN,NaN,NaN,NaN,NaN
107,108,Tcharnabroda,Roma,827-864,"[827, 828, 829, 830, 831, 832, 833, 834, 835, ...",5700.0,1492.0,4208.0,3.820375,Female,...,NaN,NaN,NaN,Tcharnabroda,Roma,NaN,NaN,NaN,NaN,NaN
108,109,Tichauer,Helen,2043-2111,"[2043, 2044, 2045, 2046, 2047, 2048, 2049, 205...",14026.0,2305.0,11721.0,6.085033,Female,...,NaN,NaN,NaN,Tichauer,Helen,NaN,NaN,NaN,NaN,NaN
109,110,Unikowski,Israel,1784-1849,"[1784, 1785, 1786, 1787, 1788, 1789, 1790, 179...",9038.0,2458.0,6580.0,3.676973,Male,...,NaN,NaN,NaN,Unikowski,Israel,yes,NaN,NaN,NaN,NaN
110,111,Warsager,Bernard,1850-1902,"[1850, 1851, 1852, 1853, 1854, 1855, 1856, 185...",9285.0,2560.0,6725.0,3.626953,Male,...,NaN,NaN,NaN,Warsager,Bernard,NaN,NaN,NaN,NaN,NaN
111,112,Weinberg,Julian,1279-1301,"[1279, 1280, 1281, 1282, 1283, 1284, 1285, 128...",3241.0,767.0,2474.0,4.225554,Male,...,NaN,NaN,NaN,Weinberg,Julian,NaN,NaN,NaN,NaN,NaN
112,113,Wilf,Jacob,1473-1499,"[1473, 1474, 1475, 1476, 1477, 1478, 1479, 148...",4036.0,1339.0,2697.0,3.014190,Male,...,NaN,NaN,NaN,Wilf,Jacob,NaN,NaN,NaN,NaN,NaN
113,114,Wolf,Isaac,2423-2497,"[2423, 2424, 2425, 2426, 2427, 2428, 2429, 243...",11173.0,2501.0,8672.0,4.467413,Male,...,NaN,NaN,NaN,Wolf,Isaac,NaN,NaN,NaN,NaN,NaN
114,115,Zeplit,Robert,,None,2142.0,1981.0,161.0,1.081272,Male,...,NaN,NaN,NaN,Zeplit,Robert,NaN,NaN,NaN,NaN,NaN
115,116,Zgnilek,Bella,2571-2591,"[2571, 2572, 2573, 2574, 2575, 2576, 2577, 257...",1596.0,1650.0,-54.0,0.967273,Female,...,NaN,NaN,NaN,Zgnilek,Bella,NaN,NaN,NaN,NaN,NaN
116,117,Zierer,Edith,2830-2854,"[2830, 2831, 2832, 2833, 2834, 2835, 2836, 283...",2237.0,1571.0,666.0,1.423934,Female,...,NaN,NaN,NaN,Zierer,Edith,yes,NaN,NaN,NaN,NaN
117,118,Zurilis,Sophia,,None,2036.0,643.0,1393.0,3.166407,Female,...,NaN,NaN,NaN,Zurilis,Sophia,NaN,NaN,NaN,NaN,NaN

In [26]:
for i in range(len(df)):
    if df.interviewee_index_range[i]=="":
        df.interviewee_index_range[i]=np.nan
    if df.interviewee_index_list[i]==None:
        df.interviewee_index_list[i]=np.nan

/Users/lizhoufan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/lizhoufan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [27]:
df

,interviewee_id,interviewee_last,interviewee_first,interviewee_index_range,interviewee_index_list,interviewee_count,interviewer_count,diff,ratio,gender,...,first_alias2,last_alias3,first_alias3,original_last,original_first,interviewed_multi_times?,where_want_to_go?,related_to,notes,additional_info
0,1,A.,Ilmar,NaN,NaN,1951.0,1395.0,556.0,1.398566,Male,...,NaN,NaN,NaN,A.,Ilmar,NaN,NaN,NaN,NaN,NaN
1,2,Barzilai,Nino,NaN,NaN,1326.0,440.0,886.0,3.013636,Male,...,NaN,NaN,NaN,Barzilai,Nino,NaN,NaN,NaN,NaN,NaN
2,3,Bassfreund,Jurgen,276-318,"[276, 277, 278, 279, 280, 281, 282, 283, 284, ...",8705.0,2231.0,6474.0,3.901838,Male,...,Jorn,Juergen,Bassfreund,Bassfreund,Jürgen,yes,NaN,NaN,NaN,NaN
3,4,Benmayor,Rita,NaN,NaN,1819.0,2219.0,-400.0,0.819739,Female,...,NaN,NaN,NaN,Benmayor,Rita,NaN,NaN,NaN,NaN,NaN
4,5,Billi,Tomas,NaN,NaN,1470.0,820.0,650.0,1.792683,Male,...,NaN,NaN,NaN,Billi,Tomas,NaN,NaN,NaN,NaN,NaN
5,6,Bisenhaus,Polia,865-886,"[865, 866, 867, 868, 869, 870, 871, 872, 873, ...",2581.0,1339.0,1242.0,1.927558,Female,...,NaN,NaN,NaN,Bisenhaus,Polia,NaN,NaN,NaN,truly multilingual transcript,NaN
6,7,B.,Janis,1033-1063,"[1033, 1034, 1035, 1036, 1037, 1038, 1039, 104...",1637.0,1212.0,425.0,1.350660,Male,...,NaN,NaN,NaN,B.,Janis,NaN,NaN,NaN,NaN,NaN
7,8,[last name unknown],Boguslaw,NaN,NaN,752.0,139.0,613.0,5.410072,Male,...,NaN,NaN,NaN,[last name unknown],Boguslaw,NaN,NaN,NaN,NaN,NaN
8,9,Bondy,Nelly,1500-1580,"[1500, 1501, 1502, 1503, 1504, 1505, 1506, 150...",10654.0,3312.0,7342.0,3.216787,Female,...,NaN,NaN,NaN,Bondy,Nelly,NaN,NaN,NaN,NaN,NaN
9,10,Borgman,[first name unknown],NaN,NaN,1027.0,680.0,347.0,1.510294,NaN,...,NaN,NaN,NaN,Borgman,[first name unknown],NaN,NaN,NaN,NaN,NaN
10,11,Bramson,Jacques,732-826,"[732, 733, 734, 735, 736, 737, 738, 739, 740, ...",15577.0,3395.0,12182.0,4.588218,Male,...,NaN,NaN,NaN,Bramson,Jacques,NaN,NaN,NaN,NaN,NaN
11,12,Braun,Anna,690-730,"[690, 691, 692, 693, 694, 695, 696, 697, 698, ...",5576.0,2706.0,2870.0,2.060606,Female,...,NaN,NaN,NaN,Braun,Anna,NaN,NaN,NaN,NaN,NaN
12,13,Breslauer,Arthur,NaN,NaN,1402.0,1199.0,203.0,1.169308,Male,...,NaN,NaN,NaN,Breslauer,Arthur,NaN,NaN,NaN,NaN,NaN
13,14,Brin,Isaac,NaN,NaN,4757.0,928.0,3829.0,5.126078,Male,...,NaN,NaN,NaN,Brin,Itzhak,NaN,NaN,NaN,NaN,NaN
14,15,Button,Eda,NaN,NaN,4802.0,1539.0,3263.0,3.120208,Female,...,NaN,NaN,NaN,Button,Eda,NaN,NaN,15,wife of 15 (may not actually be related accord...,NaN
15,16,Button,Jacob,NaN,NaN,2224.0,775.0,1449.0,2.869677,Male,...,NaN,NaN,NaN,Button,Jacob,NaN,NaN,14,husband of 14 (may not actually be related acc...,NaN
16,17,Czolopicki,Boleslaw,NaN,NaN,868.0,563.0,305.0,1.541741,Male,...,NaN,NaN,NaN,Czolopicki,Boleslaw,NaN,NaN,NaN,NaN,NaN
17,18,Deutsch,Yanusch,NaN,NaN,4387.0,1208.0,3179.0,3.631623,Male,...,NaN,NaN,NaN,Deutsch,Yanusch,NaN,NaN,NaN,NaN,NaN
18,19,Eisenberg,Kalman,2533-2570,"[2533, 2534, 2535, 2536, 2537, 2538, 2539, 254...",8603.0,1119.0,7484.0,7.688114,Male,...,NaN,NaN,NaN,Eisenberg,Kalman,NaN,NaN,NaN,NaN,NaN
19,20,Epstein-Kozlowski,Nechama,2592-2668,"[2592, 2593, 2594, 2595, 2596, 2597, 2598, 259...",13676.0,2279.0,11397.0,6.000878,Female,...,NaN,NaN,NaN,Epstein-Kozlowski,Nechama,NaN,NaN,NaN,NaN,NaN
20,21,Feneger,[first name unknown],NaN,NaN,231.0,362.0,-131.0,0.638122,Male,...,NaN,NaN,NaN,Feneger,[first name unknown],NaN,NaN,NaN,NaN,NaN
21,22,Ferber,Joseph,2855-2876,"[2855, 2856, 2857, 2858, 2859, 2860, 2861, 286...",3815.0,1074.0,2741.0,3.552142,Male,...,NaN,NaN,NaN,Ferber,Joseph,NaN,NaN,NaN,NaN,NaN
22,23,Ferdinansk,Victor,3040-3054,"[3040, 3041, 3042, 3043, 3044, 3045, 3046, 304...",1780.0,1096.0,684.0,1.624088,Male,...,NaN,NaN,NaN,Ferdinansk,Victor,NaN,NaN,NaN,NaN,NaN
23,24,Feuer,Otto,887-954,"[887, 888, 889, 890, 891, 892, 893, 894, 895, ...",9106.0,2734.0,6372.0,3.330651,Male,...,NaN,NaN,NaN,Feuer,Otto,NaN,NaN,NaN,NaN,NaN
24,25,Finkel,Nathan,NaN,NaN,1689.0,586.0,1103.0,2.882253,Male,...,NaN,NaN,NaN,Finkel,Nathan,NaN,NaN,NaN,NaN,NaN
25,26,Franz,Hildegarde,3082-3104,"[3082, 3083, 3084, 3085, 3086, 3087, 3088, 308...",2421.0,1475.0,946.0,1.641356,Female,...,NaN,NaN,NaN,Franz,Hildegarde,NaN,United States,NaN,NaN,NaN
26,27,Freilich,Esther,NaN,NaN,948.0,698.0,250.0,1.358166,Female,...,NaN,NaN,NaN,Freilich,Esther,NaN,NaN,Freida Freilich (mother) 24,NaN,NaN
27,28,Freilich,Fania,319-363,"[319, 320, 321, 322, 323, 324, 325, 326, 327, ...",10436.0,1061.0,9375.0,9.836004,Female,...,NaN,NaN,NaN,Freilich,Fania,NaN,NaN,Esther Freilich (daughter) 23,NaN,NaN
28,29,Perl,Abram,2112-2153,"[2112, 2113, 2114, 2115, 2116, 2117, 2118, 211...",5893.0,2220.0,3673.0,2.654505,Male,...,Friedman,NaN,NaN,Friedman,Baruch,NaN,Palestine,NaN,former name friedman,NaN
29,30,Frim,Leon,NaN,NaN,9023.0,1055.0,7968.0,8.552607,Male,...,NaN,NaN,NaN,Frim,Leon,NaN,NaN,NaN,look at the use of where,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Rosenfeld,Pinkhus,2877-2922,"[2877, 2878, 2879, 2880, 2881, 2882, 2883, 288...",6286.0,2224.0,4062.0,2.826439,Male,...,NaN,NaN,NaN,Rosenfeld,Pinkhus,NaN,Palestine,NaN,NaN,NaN
89,90,Rosenwasser,Irena,1205-1278,"[1205, 1206, 1207, 1208, 1209, 1210, 1211, 121...",8700.0,2869.0,5831.0,3.032415,Female,...,NaN,NaN,NaN,Rosenwasser,Irena,NaN,United States,NaN,Family in Los Angeles,NaN
90,91,Roset,Raisel,1064-1079,"[1064, 1065, 1066, 1067, 1068, 1069, 1070, 107...",1576.0,795.0,781.0,1.982390,Female,...,NaN,NaN,NaN,Roset,Raisel,NaN,NaN,NaN,NaN,NaN
91,92,Rudo,[first name unknown],NaN,NaN,1902.0,602.0,1300.0,3.159468,Female,...,NaN,NaN,NaN,Rudo,[first name unknown],NaN,NaN,NaN,"Spanish refugee taking classes at ORT,",NaN
92,93,Schacht,Nathan,NaN,NaN,1444.0,1246.0,198.0,1.158909,NaN,...,NaN,NaN,NaN,Schacht,Nathan,NaN,NaN,NaN,NaN,NaN
93,94,Schiver,Toba,NaN,NaN,2421.0,1987.0,434.0,1.218420,Female,...,NaN,NaN,NaN,Schiver,Toba,NaN,Palestine,NaN,Talk about how her younger sister is married b...,NaN
94,95,Schlaefrig,Friedrich,1135-1204,"[1135, 1136, 1137, 1138, 1139, 1140, 1141, 114...",12657.0,2164.0,10493.0,5.848891,Male,...,NaN,NaN,NaN,Schlaefrig,Friedrich,NaN,South Africa,NaN,At the end his wife passes a message along to ...,NaN
95,96,Schrameck,Abraham,NaN,NaN,2063.0,168.0,1895.0,12.279762,Male,...,NaN,NaN,NaN,Schrameck,Abraham,NaN,NaN,Father of Anne Marcelle Kahn,NaN,NaN
96,97,Schultze,Charlotte,2978-3000,"[2978, 2979, 2980, 2981, 2982, 2983, 2984, 298...",2493.0,1653.0,840.0,1.508167,Female,...,NaN,NaN,NaN,Schultze,Charlotte,NaN,United States,NaN,"Despite not being Jewish, her husband treated ...",NaN
97,98,Schwarzfitter,Jacob,1080-1134,"[1080, 1081, 1082, 1083, 1084, 1085, 1086, 108...",9490.0,1605.0,7885.0,5.912773,Male,...,NaN,NaN,NaN,Schwarzfitter,Jacob,NaN,NaN,NaN,relatives in United States,NaN
98,99,Serras,Edith,1302-1366,"[1302, 1303, 1304, 1305, 1306, 1307, 1308, 130...",10289.0,2036.0,8253.0,5.053536,Female,...,NaN,NaN,NaN,Serras,Edith,NaN,NaN,NaN,NaN,"large tattoo, is askes why her tattoo is so large"
99,100,Shachnovski,Leon,1020-1032,"[1020, 1021, 1022, 1023, 1024, 1025, 1026, 102...",1625.0,394.0,1231.0,4.124365,Male,...,NaN,NaN,NaN,Shachnovski,Leon,NaN,Germany,NaN,NaN,NaN
100,101,Silberbart,Gert,NaN,NaN,6043.0,2204.0,3839.0,2.741833,Male,...,NaN,NaN,NaN,Silberbart,Gert,NaN,NaN,NaN,NaN,NaN
101,102,Skudaikiene,Brone,NaN,NaN,579.0,486.0,93.0,1.191358,Female,...,NaN,NaN,NaN,Skudaikienė,Bronė,NaN,NaN,NaN,NaN,NaN
102,103,Sochami,Henry,NaN,NaN,1303.0,552.0,751.0,2.360507,Male,...,NaN,NaN,NaN,Sochami,Henry,NaN,NaN,NaN,NaN,NaN
103,104,Sprecher,Max,1741-1783,"[1741, 1742, 1743, 1744, 1745, 1746, 1747, 174...",8526.0,1588.0,6938.0,5.369018,Male,...,NaN,NaN,NaN,Sprecher,Max,NaN,NaN,NaN,Meyer is the middle name.,NaN
104,105,Stopnitsky,Udel,129-201,"[129, 130, 131, 132, 133, 134, 135, 136, 137, ...",14277.0,2492.0,11785.0,5.729133,Male,...,NaN,NaN,NaN,Stopnitsky,Udel,NaN,NaN,NaN,NaN,NaN
105,106,Stumachin,Lina,NaN,NaN,2650.0,581.0,2069.0,4.561102,Female,...,NaN,NaN,NaN,Stumachin,Lina,NaN,NaN,NaN,NaN,NaN
106,107,Suvalkaitis,Andrius,NaN,NaN,1828.0,579.0,1249.0,3.157168,Male,...,NaN,NaN,NaN,Suvalkaitis,Andrius,NaN,NaN,NaN,NaN,NaN
107,108,Tcharnabroda,Roma,827-864,"[827, 828, 829, 830, 831, 832, 833, 834, 835, ...",5700.0,1492.0,4208.0,3.820375,Female,...,NaN,NaN,NaN,Tcharnabroda,Roma,NaN,NaN,NaN,NaN,NaN
108,109,Tichauer,Helen,2043-2111,"[2043, 2044, 2045, 2046, 2047, 2048, 2049, 205...",14026.0,2305.0,11721.0,6.085033,Female,...,NaN,NaN,NaN,Tichauer,Helen,NaN,NaN,NaN,NaN,NaN
109,110,Unikowski,Israel,1784-1849,"[1784, 1785, 1786, 1787, 1788, 1789, 1790, 179...",9038.0,2458.0,6580.0,3.676973,Male,...,NaN,NaN,NaN,Unikowski,Israel,yes,NaN,NaN,NaN,NaN
110,111,Warsager,Bernard,1850-1902,"[1850, 1851, 1852, 1853, 1854, 1855, 1856, 185...",9285.0,2560.0,6725.0,3.626953,Male,...,NaN,NaN,NaN,Warsager,Bernard,NaN,NaN,NaN,NaN,NaN
111,112,Weinberg,Julian,1279-1301,"[1279, 1280, 1281, 1282, 1283, 1284, 1285, 128...",3241.0,767.0,2474.0,4.225554,Male,...,NaN,NaN,NaN,Weinberg,Julian,NaN,NaN,NaN,NaN,NaN
112,113,Wilf,Jacob,1473-1499,"[1473, 1474, 1475, 1476, 1477, 1478, 1479, 148...",4036.0,1339.0,2697.0,3.014190,Male,...,NaN,NaN,NaN,Wilf,Jacob,NaN,NaN,NaN,NaN,NaN
113,114,Wolf,Isaac,2423-2497,"[2423, 2424, 2425, 2426, 2427, 2428, 2429, 243...",11173.0,2501.0,8672.0,4.467413,Male,...,NaN,NaN,NaN,Wolf,Isaac,NaN,NaN,NaN,NaN,NaN
114,115,Zeplit,Robert,NaN,NaN,2142.0,1981.0,161.0,1.081272,Male,...,NaN,NaN,NaN,Zeplit,Robert,NaN,NaN,NaN,NaN,NaN
115,116,Zgnilek,Bella,2571-2591,"[2571, 2572, 2573, 2574, 2575, 2576, 2577, 257...",1596.0,1650.0,-54.0,0.967273,Female,...,NaN,NaN,NaN,Zgnilek,Bella,NaN,NaN,NaN,NaN,NaN
116,117,Zierer,Edith,2830-2854,"[2830, 2831, 2832, 2833, 2834, 2835, 2836, 283...",2237.0,1571.0,666.0,1.423934,Female,...,NaN,NaN,NaN,Zierer,Edith,yes,NaN,NaN,NaN,NaN
117,118,Zurilis,Sophia,NaN,NaN,2036.0,643.0,1393.0,3.166407,Female,...,NaN,NaN,NaN,Zurilis,Sophia,NaN,NaN,NaN,NaN,NaN

In [28]:
df.to_csv("Boder_meta_with_index.csv", index=False)